### ISSUE TITLE
Multiple citations? 

### ISSUE THREAD

**Issue by iandol** [teertinker/JabRef_LibreOffice_Converter#1]
If I have something like `\cite{doe2022,roe2021}` I seem to only get the correct `JR_100` etc. prepended to the first citation. How to deal with multiple citations in the same block?

**Comment by teertinker** [comment]
Sorry, but I cannot reproduce your bug. On my platform a Jabrefkey looks like yours:
`\cite{Leisering1997,Struck2001}`
When copying this key to a LibreOffice document, and  applying the converter to change the key to a citation field, both references get converted properly. Both references are also shown in the bibliography.

**Comment by iandol** [comment]
Here is the reference field I get when converting `\cite{lau2022,derrien2022}`:

![Screenshot 2022-09-23 at 09 08 12](https://user-images.githubusercontent.com/153905/191917997-a081dfe1-75ab-46d9-9af6-98b5851d4847.png)

ODT: [LibreOfficeCite.odt](https://github.com/teertinker/JabRef_LibreOffice_Converter/files/9631952/LibreOfficeCite.odt)

Now I don't really understand what the `JR_cite100_1_` prefix is doing, but it is not added to the `derrien2022` reference identifier. The reason I raised this is that sometimes when using JabRef to format citations I get errors for the unprefixed reference, telling me `derrien2022` is not found even though it is in my database. Perhaps this is unrelated but I thought I would ask.

**Comment by iandol** [comment]
added this to #3

**Comment by iandol** [comment]
OK, the problem I realise that caused my Jabref issue is spaces in multiple cites, so `\cite{lau2022, derrien2022}` converts to `\cite{JR_cite100_1_lau2022, derrien2022}` but JabRef complains that ` derrien2022` in not found

![Screenshot 2022-09-23 at 10 06 58](https://user-images.githubusercontent.com/153905/191932002-517fd3db-a5b9-4e74-8dda-e7d493211e81.png)

So I think the prefixes were not the issue. Perhaps you could remove spaces after commas just in case. I will close this if the prefixes are correct.

**Comment by teertinker** [comment]
Your example works fine on my pc without any errors. After creating some test entries with your keys. JabRef creates a proper bibliography.

**Comment by iandol** [comment]
Ok thank you!

**Comment by teertinker** [comment]
Probably you are right. The counter starting with 100 may not be handled correctly when converting back and forth. The identifier for the citation-type however is an important tool from my point of view. Otherwise you would loose this information. With my limited skills in programming and a small time budget, I can't improve the code right now. 

    On Friday, September 23, 2022 at 10:27:43 AM GMT+2, Ian Max Andolina ***@***.***> wrote:  
 
 


Another issue is if I convert back to text the the 100_1_ prefix remains, however if I now copy and past that ref to another part of the doc, then LibreOffice will complain that there are duplicates:
This is a test cite \cite{100_1_lau2022,derrien2022}. Some more stuff to cite here \cite{100_1_melloni2021}. 
And more stuff \cite{100_1_derrien2022}. Again some more \cite{101_1_lau2022}. Some more by \cite{101_1_melloni2021,derrien2022,lau2022}.

Would it not be better to deconvert back to the citekeys alone?
